# Generated by Django 4.1.1 on 2022-10-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=255)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=255)),
                ('degree', models.CharField(choices=[('1', 'bsc'), ('2', 'bcom')], max_length=20)),
                ('date_field', models.DateField()),
            ],
        ),
    ]
